const DOOR_AUDIO_MODES={silent:'Silenciosa',random:'Aleatória',careless:'Sem cuidado'};
let doorAudioMode='silent';
function chooseDoorAudio(mode,roll=Math.random()){return mode==='silent'?'silent':mode==='careless'?'careless':roll<0.5?'silent':'careless'}
const DOOR_LEVELS={
 easy:{label:'Fácil',maxSpeed:520,maxJump:60,reverse:14,cross:20,pauseDrift:15,description:'Menor sensibilidade: mais tolerância à velocidade e aos desvios.'},
 medium:{label:'Médio',maxSpeed:360,maxJump:45,reverse:9,cross:13,pauseDrift:10,description:'Sensibilidade equilibrada: movimentos lentos e precisos.'},
 hard:{label:'Difícil',maxSpeed:220,maxJump:28,reverse:5,cross:7,pauseDrift:6,description:'Alta sensibilidade: mova muito devagar e mantenha a direção.'}
};
let doorDifficulty='medium',previousDoorSequence='';
function randomDoorSequence(){
 const permutations=[];
 function permute(prefix,rest){if(!rest.length){if(prefix.join(',')!==previousDoorSequence)permutations.push(prefix);return}rest.forEach((key,i)=>permute([...prefix,key],rest.filter((_,j)=>i!==j)))}
 permute([],['right','down','left','up']);
 const chosen=permutations[Math.floor(Math.random()*permutations.length)];previousDoorSequence=chosen.join(',');return chosen;
}
// Motion is measured in CSS pixels, over an 80 ms rolling window.
class DoorMotion {
 constructor(sequence,difficulty='medium'){this.settings=DOOR_LEVELS[difficulty]||DOOR_LEVELS.medium;this.sequence=sequence;this.step=0;this.active=false;this.distance=64;this.maxSpeed=this.settings.maxSpeed;this.samples=[];this.pauseUntil=0;}
 begin(x,y,t){this.active=true;this.origin={x,y};this.last={x,y,t};this.samples=[{x,y,t}];}
 move(x,y,t){if(!this.active)return{};const prev=this.last, jump=Math.hypot(x-prev.x,y-prev.y);this.last={x,y,t};this.samples.push({x,y,t});while(this.samples.length>2&&this.samples[1].t<t-80)this.samples.shift();let path=0;for(let i=1;i<this.samples.length;i++)path+=Math.hypot(this.samples[i].x-this.samples[i-1].x,this.samples[i].y-this.samples[i-1].y);const elapsed=t-this.samples[0].t;let speed=elapsed>=35?path/elapsed*1000:0;if(jump>this.settings.maxJump||(elapsed>=35&&speed>this.maxSpeed))return this.fail('Movimento brusco: você fez a fechadura estalar.');
 if(this.pauseUntil&&t<this.pauseUntil){if(Math.hypot(x-this.origin.x,y-this.origin.y)>this.settings.pauseDrift)return this.fail('Você se moveu durante a pausa. Espere a próxima direção.');return{pause:true,speed};}
 if(this.pauseUntil){this.pauseUntil=0;this.origin={x:prev.x,y:prev.y};}
 const [dx,dy]=this.sequence[this.step].v;let along=(x-this.origin.x)*dx+(y-this.origin.y)*dy;let cross=Math.abs((x-this.origin.x)*dy-(y-this.origin.y)*dx);if(along < -this.settings.reverse||cross>this.settings.cross)return this.fail('Direção errada: a trava voltou ao lugar.');if(along>=this.distance){this.step++;this.origin={x,y};this.samples=[{x,y,t}];if(this.step===this.sequence.length){this.active=false;return{success:true,speed,progress:100}}this.pauseUntil=t+650;return{pause:true,advanced:true,speed,progress:0};}return{speed,progress:Math.max(0,along/this.distance*100)};
 }
 fail(reason){this.active=false;return{failure:reason}}
}
function mountDoorChallenge(){
 $('title').textContent='A porta que escuta';$('story').textContent='A fechadura está prestes a ceder. Conduza o mouse com cuidado: qualquer movimento brusco ou na direção errada denuncia sua presença.';$('clue').hidden=true;$('hint').hidden=true;$('badge').textContent='DESTREZA / MOUSE';$('case').textContent='FECHADURA SENSÍVEL';
 const dirs={right:{label:'Direita',arrow:'→',v:[1,0]},down:{label:'Baixo',arrow:'↓',v:[0,1]},left:{label:'Esquerda',arrow:'←',v:[-1,0]},up:{label:'Cima',arrow:'↑',v:[0,-1]}};
 let seq=[],motion=new DoorMotion(seq,doorDifficulty),pointer=null,tries=0,pauseTimer=null,speedTimer=null;const lifecycle=new AbortController();const opts={signal:lifecycle.signal};
 $('play').innerHTML=`<div class="door-settings"><fieldset id="door-difficulty" class="door-difficulty"><legend>Dificuldade · sensibilidade do mouse</legend>${Object.entries(DOOR_LEVELS).map(([key,level])=>`<label><input type="radio" name="door-level" value="${key}" ${doorDifficulty===key?'checked':''}>${level.label}</label>`).join('')}<p id="door-level-description"></p></fieldset><fieldset id="door-audio-mode" class="door-difficulty"><legend>Som ao abrir a porta</legend>${Object.entries(DOOR_AUDIO_MODES).map(([key,label])=>`<label><input type="radio" name="door-audio" value="${key}" ${doorAudioMode===key?'checked':''}>${label}</label>`).join('')}<p>Aleatória: 50% de chance para cada áudio.</p></fieldset></div><div id="door-immersive" class="door-game"><div id="door-stage" class="door-stage"><div class="door-frame"><div class="door-beyond"><span>PASSAGEM<br>LIBERADA</span></div><img id="door-leaf" class="door-leaf" src="door.png" alt="Porta antiga de madeira fechada" draggable="false"></div><button id="door-grip" class="door-grip" aria-label="Segure o botão esquerdo do mouse aqui para começar">SEGURE AQUI</button><span id="door-state" class="door-state">FECHADA</span></div><div class="door-instructions"><button id="door-exit" class="text-button door-exit">Sair da tela cheia · Esc</button><div class="eyebrow">INSTRUÇÕES DA FECHADURA</div><p class="door-how">Segure o botão esquerdo no círculo e mantenha-o pressionado até o fim. Mova devagar na direção indicada. Ao concluir cada movimento, <strong>pare e espere o próximo comando.</strong></p><ol id="door-sequence">${seq.map((d,i)=>`<li id="door-step-${i}"><span>${d.arrow}</span>${d.label}<small>${i+1}/4</small></li>`).join('')}</ol><div id="door-command" role="status" aria-live="polite">Aguardando sua mão</div><label class="meter-label" for="door-progress">Movimento atual <span id="door-percent">0%</span></label><progress id="door-progress" max="100" value="0"></progress><label class="meter-label" for="door-speed">Velocidade <span id="door-speed-text">Parado</span></label><meter id="door-speed" min="0" max="360" low="190" high="290" optimum="100" value="0"></meter><p class="door-tip">Devagar e em linha reta. Você pode parar durante um movimento. Sair da área ou soltar antes do fim encerra a tentativa.</p><button id="door-retry" class="door-retry">Reiniciar tentativa</button><p id="door-immersive-result" role="status"></p><p class="door-device">Mouse ou trackpad. Cada tentativa recebe uma nova sequência.</p></div></div>`;
 const stage=$('door-stage'),grip=$('door-grip'),surface=$('door-immersive');
 let preparing=false,transitionId=0,lastClient=null,virtual={x:0,y:0},audioContext=null,sound=null;
 let soundVersion=0,decoded=null;
 const audioFiles={silent:'audio/silencioso.mp3',careless:'audio/sem-cuidado.mp3'};
 const audioData=Object.fromEntries(Object.entries(audioFiles).map(([key,url])=>[key,fetch(url).then(r=>{if(!r.ok)throw Error('Áudio indisponível');return r.arrayBuffer()}).catch(()=>null)]));
 function unlockAudio(){try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});decoded??=Object.fromEntries(Object.entries(audioData).map(([key,promise])=>[key,promise.then(data=>data?audioContext.decodeAudioData(data):null).catch(()=>null)]))}catch{}}
 async function creak(){stopSound();const version=soundVersion,key=chooseDoorAudio(doorAudioMode);try{const buffer=await decoded?.[key];if(version!==soundVersion||lifecycle.signal.aborted)return;if(!buffer||!audioContext)throw Error('Áudio indisponível');await audioContext.resume();if(version!==soundVersion||lifecycle.signal.aborted)return;sound=audioContext.createBufferSource();sound.buffer=buffer;sound.connect(audioContext.destination);sound.start()}catch{if(version===soundVersion&&!lifecycle.signal.aborted)$('door-immersive-result').textContent+=' Não foi possível reproduzir o áudio. Recarregue a página e tente novamente.'}}
 function stopSound(){soundVersion++;try{sound?.stop()}catch{}sound=null}
 function leaveImmersive(){transitionId++;preparing=false;if(motion.active)result(false,'Você saiu da tela cheia antes de concluir.');surface.classList.remove('immersive','playing');document.body.classList.remove('door-fullscreen');if(document.fullscreenElement===surface)document.exitFullscreen?.().catch(()=>{});}
 async function enterImmersive(){const id=++transitionId;preparing=true;surface.classList.add('immersive','playing');document.body.classList.add('door-fullscreen');$('door-command').textContent='Mantenha pressionado. Preparando a fechadura…';try{if(!document.fullscreenElement&&surface.requestFullscreen)await surface.requestFullscreen()}catch{}await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(id!==transitionId||!motion.active)return;const r=stage.getBoundingClientRect();virtual={x:r.width/2,y:r.height/2};grip.style.left=virtual.x+'px';grip.style.top=virtual.y+'px';motion.begin(virtual.x,virtual.y,performance.now());lastClient=null;preparing=false;command();}
 $('door-exit').onclick=leaveImmersive;
 document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&!preparing&&surface.classList.contains('immersive'))leaveImmersive()},opts);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&surface.classList.contains('immersive'))leaveImmersive()},opts);

 function release(){const id=pointer;pointer=null;if(id!==null&&grip.hasPointerCapture?.(id))grip.releasePointerCapture(id)}
 function clearTimers(){clearTimeout(pauseTimer);clearTimeout(speedTimer)}
 function renderSteps(){seq.forEach((d,i)=>{$(`door-step-${i}`).className=i<motion.step?'complete':i===motion.step&&motion.active?'current':''})}
 function result(ok,reason){motion.active=false;preparing=false;transitionId++;surface.classList.remove('playing');if(ok)creak();$('door-immersive-result').textContent=ok?'A porta se abriu. Você pode soltar o mouse.':reason+' A porta continua fechada.';$('door-difficulty').disabled=false;$('door-audio-mode').disabled=false;clearTimers();release();grip.hidden=true;stage.classList.toggle('opened',ok);stage.classList.toggle('failed',!ok);$('door-state').textContent=ok?'ABERTA':'CONTINUA FECHADA';$('door-leaf').alt=ok?'Porta antiga aberta':'Porta antiga fechada';$('door-command').textContent=ok?'Você abriu a porta.':'Tentativa encerrada.';feedback(ok?'A porta se abre.':'Você falhou. A porta continua fechada.',ok?'A última trava cede. A passagem está liberada.':reason+' Reinicie para tentar novamente.',!ok);$('attempts').textContent=`TENTATIVA ${tries} · ${ok?'SUCESSO':'FALHA'}`;renderSteps()}
 function command(){if(motion.active){$('door-command').textContent=`${seq[motion.step].arrow} Mova devagar para ${seq[motion.step].label.toLowerCase()}`;renderSteps()}}
 function reset(){transitionId++;preparing=false;surface.classList.remove('playing');stopSound();$('door-immersive-result').textContent='';clearTimers();motion.active=false;release();seq=randomDoorSequence().map(k=>dirs[k]);motion=new DoorMotion(seq,doorDifficulty);$('door-sequence').innerHTML=seq.map((d,i)=>`<li id="door-step-${i}"><span>${d.arrow}</span>${d.label}<small>${i+1}/4</small></li>`).join('');$('door-difficulty').disabled=false;$('door-audio-mode').disabled=false;$('door-level-description').textContent=motion.settings.description;$('badge').textContent='DESTREZA / '+motion.settings.label.toUpperCase();const meter=$('door-speed');meter.max=motion.maxSpeed;meter.low=motion.maxSpeed*.53;meter.high=motion.maxSpeed*.81;meter.optimum=motion.maxSpeed*.28;stage.classList.remove('opened','failed');grip.hidden=false;grip.style.left='50%';grip.style.top='50%';grip.textContent='SEGURE AQUI';$('door-state').textContent='FECHADA';$('door-leaf').alt='Porta antiga de madeira fechada';$('door-command').textContent='Aguardando sua mão';$('door-progress').value=0;$('door-percent').textContent='0%';$('door-speed').value=0;$('door-speed-text').textContent='Parado';$('feedback').replaceChildren();$('attempts').textContent='SEGURE O CÍRCULO PARA COMEÇAR';renderSteps()}
 grip.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){feedback('Use um mouse ou trackpad.','Este desafio acompanha os movimentos do cursor.');return}if(e.button!==0||motion.active)return;e.preventDefault();unlockAudio();clearTimers();tries++;$('door-difficulty').disabled=true;$('door-audio-mode').disabled=true;pointer=e.pointerId;grip.setPointerCapture(pointer);motion.begin(0,0,e.timeStamp);lastClient={x:e.clientX,y:e.clientY};grip.textContent='◉';$('feedback').replaceChildren();$('attempts').textContent=`TENTATIVA ${tries} · EM ANDAMENTO`;enterImmersive()},opts);
 grip.addEventListener('pointermove',e=>{if(!motion.active||e.pointerId!==pointer)return;e.preventDefault();if(preparing){lastClient={x:e.clientX,y:e.clientY};return}if(!lastClient){lastClient={x:e.clientX,y:e.clientY};return}virtual.x+=e.clientX-lastClient.x;virtual.y+=e.clientY-lastClient.y;lastClient={x:e.clientX,y:e.clientY};const r=stage.getBoundingClientRect();if(virtual.x<0||virtual.x>r.width||virtual.y<0||virtual.y>r.height){result(false,'O cursor saiu da área da porta.');return}const res=motion.move(virtual.x,virtual.y,e.timeStamp);grip.style.left=virtual.x+'px';grip.style.top=virtual.y+'px';$('door-speed').value=Math.min(motion.maxSpeed,res.speed||0);$('door-speed-text').textContent=res.speed>motion.maxSpeed*.81?'Cuidado!':res.speed>0?'Suave':'Parado';clearTimeout(speedTimer);speedTimer=setTimeout(()=>{if(motion.active){$('door-speed').value=0;$('door-speed-text').textContent='Parado'}},130);if(res.failure){result(false,res.failure);return}if(res.progress!==undefined){$('door-progress').value=res.progress;$('door-percent').textContent=Math.round(res.progress)+'%'}if(res.success){result(true);return}if(res.advanced){renderSteps();$('door-command').textContent='Pare. A próxima trava está cedendo…';pauseTimer=setTimeout(command,650)}},opts);
 grip.addEventListener('pointerup',()=>{if(motion.active)result(false,'Você soltou a fechadura antes de completar a sequência.')},opts);
 for(const event of ['pointercancel','lostpointercapture'])grip.addEventListener(event,()=>{if(motion.active)result(false,'O controle do cursor foi interrompido.')},opts);
 window.addEventListener('blur',()=>{if(motion.active)result(false,'A tentativa foi interrompida ao sair da janela.')},opts);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&motion.active)result(false,'A tentativa foi interrompida ao trocar de aba.')},opts);
 $('door-audio-mode').addEventListener('change',e=>{if(motion.active||!Object.hasOwn(DOOR_AUDIO_MODES,e.target.value))return;stopSound();doorAudioMode=e.target.value},opts);$('door-difficulty').addEventListener('change',e=>{if(motion.active||!DOOR_LEVELS[e.target.value])return;doorDifficulty=e.target.value;reset()},opts);$('door-retry').onclick=reset;window.cleanupDoor=()=>{motion.active=false;leaveImmersive();stopSound();audioContext?.close().catch(()=>{});clearTimers();release();lifecycle.abort();window.cleanupDoor=null};reset();
}
